# Site settings
title: "lux:cipher"
bye_message: "Thx!"
baseurl: "/"
url: "https://alt5474n.github.io"
#disqus: gjuniioor

# Header settings
nick: "luxcipher"
mail:
    domain: "protonmail"
    ext: "com"
    #source_code:
    #server: "github.com"
    #nick: "gjuniioor"
    #blog:
    #server: "wordpress.com"
    #nick: "gjuniioor"
    #fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
