# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: lux:cipher
description: Nothing. And everything.
author: void nihil
url: "https://luxcipher.com"
markdown: kramdown

header_pages:
  - index.md
  - about.md

footer: '...only I and this black void have ever been.'

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  - jekyll-feed

